# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER gulimall

# 挂载目录
VOLUME /home/gulimall
# 创建目录
RUN mkdir -p /home/gulimall
# 指定路径
WORKDIR /home/gulimall
# 复制jar文件到路径
COPY ./jar/gulimall-modules-system.jar /home/gulimall/gulimall-modules-system.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","gulimall-modules-system.jar"]